# Generated by Django 5.0.2 on 2025-04-28 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("portfolio", models.URLField(blank=True)),
                (
                    "preferred_job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferred_location", models.CharField(blank=True, max_length=100)),
                ("expected_salary", models.CharField(blank=True, max_length=50)),
                (
                    "availability_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediately", "Immediately"),
                            ("1_week", "1 Week"),
                            ("2_weeks", "2 Weeks"),
                            ("1_month", "1 Month"),
                            ("not_available", "Not Available"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remote_work", models.BooleanField(default=False)),
                (
                    "resume_privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("connections", "Connections Only"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
