# Generated by Django 5.0.2 on 2025-03-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="address",
            field=models.CharField(default="Unknown Address", max_length=255),
        ),
        migrations.AddField(
            model_name="cv",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="cv",
            name="full_name",
            field=models.CharField(default="Tonny Toroitich", max_length=255),
        ),
        migrations.AddField(
            model_name="cv",
            name="phone_number",
            field=models.CharField(default="07-xx-xxx-xxx", max_length=15),
        ),
        migrations.AddField(
            model_name="cv",
            name="professional_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="content",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cv",
            name="generated_file",
            field=models.FileField(blank=True, null=True, upload_to="generated_cvs/"),
        ),
        migrations.AlterField(
            model_name="cv",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cvs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("field", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="documents.cv"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="documents.cv"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
