# Generated by Django 5.0.2 on 2025-03-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_coverletter_generated_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.cv",
            ),
        ),
    ]
