# Generated by Django 5.0.2 on 2025-03-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_coverletter_cv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewquestion",
            name="category",
        ),
        migrations.DeleteModel(
            name="InterviewPrep",
        ),
        migrations.DeleteModel(
            name="InterviewQuestion",
        ),
        migrations.DeleteModel(
            name="JobCategory",
        ),
    ]
