# Generated by Django 5.0.2 on 2025-03-28 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_remove_interviewquestion_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvtemplate",
            name="template_file",
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="css_template",
            field=models.FileField(
                blank=True, null=True, upload_to="cv_templates/css/"
            ),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="html_template",
            field=models.FileField(
                blank=True, null=True, upload_to="cv_templates/html/"
            ),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cvtemplate",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cv_templates/previews/"
            ),
        ),
    ]
