# Generated by Django 5.0.2 on 2025-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_cvtemplate_template_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cv",
            options={"verbose_name": "CV", "verbose_name_plural": "CVs"},
        ),
        migrations.AlterModelOptions(
            name="cvtemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="cv",
            name="generated_file",
            field=models.FileField(blank=True, null=True, upload_to="generated_cvs/"),
        ),
    ]
