# Generated by Django 5.0.2 on 2025-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_cv_options_alter_cvtemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="document",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
        migrations.RemoveField(
            model_name="document",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="document",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_parsed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
