# Generated by Django 5.0.2 on 2025-04-02 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
