# Generated by Django 5.0.2 on 2025-03-17 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_rename_position_interviewprep_job_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewprep",
            name="interview_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
