# Generated by Django 5.0.2 on 2025-03-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_alter_interviewprep_interview_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewprep",
            name="interview_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
