# Generated by Django 5.0.2 on 2025-03-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_alter_interviewprep_interview_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewprep",
            options={"ordering": ["-interview_date"]},
        ),
    ]
