# Generated by Django 5.0.2 on 2025-03-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0005_alter_interviewprep_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="interviewprep",
            name="interview_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interviewprep",
            name="questions",
            field=models.ManyToManyField(blank=True, to="interviews.interviewquestion"),
        ),
    ]
