# Generated by Django 5.0.2 on 2025-03-19 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0006_alter_industry_description_alter_industry_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewprep",
            name="interview_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
