# Generated by Django 5.0.2 on 2025-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0007_alter_interviewprep_interview_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="interviewprep",
            name="interview_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="interviewprep",
            name="questions",
            field=models.ManyToManyField(to="interviews.interviewquestion"),
        ),
    ]
