# Generated by Django 5.0.2 on 2025-03-21 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0008_alter_industry_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="interviewprep",
            name="interview_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="interviewprep",
            name="questions",
            field=models.ManyToManyField(blank=True, to="interviews.interviewquestion"),
        ),
    ]
