# Generated by Django 5.0.2 on 2025-03-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0009_alter_industry_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewprep",
            options={},
        ),
    ]
